### ISSUE TITLE
Rename it in plugin list

### ISSUE THREAD

**Issue by slavkoja** [RocketMan/plugin-imap-user-auth#3]
The plugin name in Kanboard's plugin list is ugly "plugin-imap-user-auth".

IMO better will be to name (list) it with the same name as its directory i.e. "IMAPUserAuth" or perhaps with spaces "IMAP User Auth".

**Comment by RocketMan** [comment]
Good one, I had not noticed that.  Change deployed in release v1.0.2.

The name in the plugin list and the README are now a more user friendly name.
